### ISSUE TITLE
List events on website

### ISSUE THREAD

**Issue by jtellew** [ucsb-cs56-f18/ucsb-cs56-events-calendar#2]
- [x] Choose group at UCSB to use sample events
- [x] Find 5 events and relevant information
- [x] Add events and descriptions to the webpage

**Comment by ryangormley81** [comment]
working on this issue now, creating a branch called sample_events_list and using mens basketball schedule. Side note, this website already has a calendar of all ucsb sports http://www.ucsbgauchos.com/composite?y=2018&m=11

**Comment by shao158** [comment]
Congratulation!
100 points are awarded.
