### ISSUE TITLE
Create a calendar template from scratch using html

### ISSUE THREAD

**Issue by ryangormley81** [ucsb-cs56-f18/ucsb-cs56-events-calendar#7]
- [x] Create a table for this month labeled correctly for Month and days of week that is viewed on the Events page
- [x] Propagate table for the rest of this quarter
- [x] Add events to the calendar
- [ ] Add the sample events and descriptions from issue #2 to the calendar
- [ ] After completing issue #6 add the gathered data to the calendar by hand marking where it came from

**Comment by jtellew** [comment]
Do you think it would be better to try and [embed a Google Calendar widget](https://support.google.com/calendar/answer/41207?hl=en)?  Then we might be able to make it so people can also export an event to their own calendar easily.

**Comment by scottpchow23** [comment]
This needs to be made more specific/cut down to one objective.

Ideally one ticket would focus on: "Add a calendar widget/view with template data to example.url/here"

And another would focus on: "Using data from #6 populate some data into the calendar view."

Note that these would be example titles and that the bodies of the issues would be more specific about requirements/expected behaviors.

**Comment by ryangormley81** [comment]
updated and broken into two issues. This issue is a handmade calendar template, the other issue is using the google calendar. I think it would be best for us to explore both options to see which is a better fit for our end goal

**Comment by scottpchow23** [comment]
Alright I would lean towards trying the Google Calendar widget first though. Also the 2nd point seems like that process should be automated through code instead of adding additional information by hand.

**Comment by ryangormley81** [comment]
opened pull request
We did not complete the fourth checkbox because we have new sample events
We did not complete the fifth checkbox because we have not finished scraping but the rest of this issue is complete

**Comment by scottpchow23** [comment]
I'll accept this issues as is but it's going to be 200 points instead.

**Comment by shao158** [comment]
200 points awarded. Congrats!

Edited: Should be 400 points as Scott said.

**Comment by scottpchow23** [comment]
My mistake, this should have stayed at 400. This issue also included resolving JSON to Event objects.
